# Generated by Django 5.1.4 on 2025-01-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_auto_20220417_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteBanner',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
