# Generated by Django 5.1.5 on 2025-01-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_delete_sitebanner_delete_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLink',
        ),
 
    ]
