# Generated by Django 5.1.5 on 2025-01-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_delete_footerlink_delete_footerlinkbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLinkBox',
        ),
    ]
