# Generated by Django 5.1.5 on 2025-03-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0004_alter_userprofile_image'),
        ('movakel_module', '0093_alter_defensedocument_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='contactus',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel', verbose_name='موکل'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه موکل'),
        ),
    ]
