# Generated by Django 5.1.5 on 2025-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0005_delete_userprofile_contactus_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='is_read_by_admin',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='response',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
    ]
