# Generated by Django 5.1.5 on 2025-03-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0006_remove_contactus_created_date_remove_contactus_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'شماره تماس موکل', 'verbose_name_plural': 'شماره تماس موکلین'},
        ),
    ]
