# Generated by Django 5.1.5 on 2025-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0007_alter_contactus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام تماس'),
        ),
    ]
