# Generated by Django 5.1.5 on 2025-03-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0008_contactus_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه '),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام تماس گیرنده'),
        ),
    ]
