# Generated by Django 5.1.5 on 2025-04-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0009_alter_contactus_client_phone_number_and_more'),
        ('movakel_module', '0171_remove_defensedocument_defense_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'مراجعه کننده', 'verbose_name_plural': 'دفترچه تلفن'},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='client_phone_number',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel', verbose_name='مراجعه کننده'),
        ),
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contact_module.contactus', verbose_name='مراجعه کننده')),
            ],
            options={
                'verbose_name': 'شماره تماس',
                'verbose_name_plural': 'شماره\u200cهای تماس',
            },
        ),
    ]
