# Generated by Django 5.1.5 on 2025-04-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0010_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactphonenumber',
            options={'verbose_name': 'شماره تماس اضافی', 'verbose_name_plural': 'شماره تماس\u200cهای اضافی'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'شماره تماس موکل', 'verbose_name_plural': 'شماره تماس موکلین'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='contactphonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_module.contactus', verbose_name='تماس مربوط به'),
        ),
        migrations.AlterField(
            model_name='contactphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
    ]
