# Generated by Django 5.1.5 on 2025-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0011_alter_contactphonenumber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'شماره تماس موکل', 'verbose_name_plural': 'دفترچه تلفن موکلین'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contact_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='نام و نام خانوادگی( عدم وکالت ) '),
        ),
    ]
