# Generated by Django 5.1.5 on 2025-02-07 14:30

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شعبه')),
                ('category', models.CharField(max_length=255, verbose_name='نوع دسته\u200cبندی')),
                ('branch_number', models.IntegerField(verbose_name='شماره شعبه')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعبات',
            },
        ),
        migrations.CreateModel(
            name='DefenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('initial', 'بدوی'), ('appeal', 'اعتراض'), ('enforcement', 'اجرای احکام')], max_length=500, verbose_name='مرحله')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه مرحله')),
                ('content', models.TextField(verbose_name='متن لایحه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('mechanized_number', models.CharField(blank=True, max_length=18, null=True, verbose_name='شماره مکانیزه')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdf/', verbose_name='فایل PDF')),
                ('word_file', models.FileField(blank=True, null=True, upload_to='documents/word/', verbose_name='فایل Word')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'تنظیم لایحه',
                'verbose_name_plural': 'تنظیم لایحه ها',
            },
        ),
        migrations.CreateModel(
            name='MovakelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='MovakelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام پرونده')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پیش\u200cفرض')),
                ('counseling', models.BooleanField(default=False, verbose_name='مشاوره')),
                ('bill', models.BooleanField(default=False, verbose_name='لایحه')),
                ('check_documents', models.BooleanField(default=False, verbose_name='بررسی مدارک')),
                ('contract', models.BooleanField(default=False, verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'نوع پرونده',
                'verbose_name_plural': 'نوع پرونده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file', models.FileField(upload_to='pdfs/', verbose_name='فایل PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فایل pdf ',
                'verbose_name_plural': '  فایل های pdf',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movakel', models.CharField(max_length=255, verbose_name='نام پرونده')),
                ('consultation_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ مشاوره')),
                ('document_review_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ بررسی مدارک')),
                ('contract_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ قرارداد')),
                ('agreed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حق\u200cالوکاله توافقی')),
                ('initial_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی')),
                ('defense_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه لایحه')),
                ('appeal_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه اعتراض')),
                ('enforcement_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه اجرای احکام')),
                ('court_review_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مطالعه پرونده در دادگاه')),
                ('petition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تنظیم لایحه یا شکواییه')),
            ],
            options={
                'verbose_name': 'نوع خدمت',
                'verbose_name_plural': 'انواع خدمات',
            },
        ),
        migrations.CreateModel(
            name='Movakel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='نام موکل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/movakels', verbose_name='تصویر پرونده')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('presenter', models.CharField(max_length=300, null=True, verbose_name='معرف')),
                ('age', models.CharField(max_length=3, verbose_name='سن')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پیش\u200cفرض')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('file_number', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن ثابت')),
                ('mechanized_number', models.CharField(max_length=18, null=True, verbose_name='شماره مکانیزه')),
                ('archive_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی')),
                ('short_description', models.CharField(db_index=True, max_length=360, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(db_index=True, verbose_name='توضیحات اصلی')),
                ('slug', models.SlugField(blank=True, default='', max_length=200, verbose_name='عنوان در URL')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('total_amount', models.IntegerField(default=100000, verbose_name='مبلغ توافق شده')),
                ('received_amount', models.IntegerField(default=50000, verbose_name='مبلغ دریافت شده')),
                ('acceptance_method', models.CharField(blank=True, choices=[('phone', 'تلفنی'), ('in_person', 'حضوری'), ('online', 'آنلاین')], max_length=50, null=True, verbose_name='نحوه پذیرش')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدی'), ('check', 'چک'), ('card', 'کارت به کارت'), ('pos', 'دستگاه پز'), ('bank_transfer', 'انتقال بانکی'), ('credit_card', 'کارت اعتباری')], max_length=50, null=True, verbose_name='نحوه پرداخت')),
                ('payment_amount', models.IntegerField(default=0, verbose_name='مبلغ پرداختی')),
                ('final_result', models.TextField(blank=True, null=True, verbose_name='نتیجه نهایی پرونده')),
                ('case_steps', models.JSONField(blank=True, default=list, verbose_name='مراحل پرونده')),
                ('hearing_date', models.DateField(blank=True, null=True, verbose_name='وقت رسیدگی')),
                ('primary_court_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره دادنامه بدوی')),
                ('primary_court_notification_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ بدوی')),
                ('appeal_court_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره دادنامه تجدیدنظر')),
                ('appeal_court_notification_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ تجدیدنظر')),
                ('executive_case_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره اجرائیه پرونده')),
                ('executive_case_notification_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ اجرائیه پرونده')),
                ('supervision_date', models.DateField(blank=True, null=True, verbose_name='وقت نظارت')),
                ('defensedocument_set', models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.defensedocument')),
                ('category', models.ManyToManyField(related_name='movakel_categories', to='movakel_module.movakelcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakeltype', verbose_name='نوع پرونده')),
            ],
            options={
                'verbose_name': 'پرونده',
                'verbose_name_plural': 'پرونده\u200cها',
            },
        ),
        migrations.AddField(
            model_name='defensedocument',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_documents', to='movakel_module.movakel', verbose_name='موکل'),
        ),
        migrations.CreateModel(
            name='MovakelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/movakel-gallery', verbose_name='تصویر')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='MovakelPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('payment_date', django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('check', 'چک'), ('card', 'کارت به کارت'), ('pos', 'دستگاه پز'), ('bank_transfer', 'انتقال بانکی'), ('credit_card', 'کارت اعتباری')], max_length=50, verbose_name='نحوه پرداخت')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده / نشده')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movakelpayments', to='movakel_module.movakel', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='MovakelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movakel_tags', to='movakel_module.movakel')),
            ],
            options={
                'verbose_name': 'تگ پرونده',
                'verbose_name_plural': 'تگ های پرونده ها',
            },
        ),
        migrations.CreateModel(
            name='MovakelVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بازدید پرونده',
                'verbose_name_plural': 'بازدیدهای پرونده',
            },
        ),
        migrations.AddField(
            model_name='movakel',
            name='visits',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.movakelvisit'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='pdf_files',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.pdffile', verbose_name='فایل\u200cهای PDF'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movakels', to='movakel_module.servicetype', verbose_name='نوع خدمت'),
        ),
        migrations.CreateModel(
            name='MovakelBranchArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_no', models.CharField(max_length=20, verbose_name='شماره بایگانی')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_archives', to='movakel_module.branch', verbose_name='شعبه')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_archives', to='movakel_module.movakel', verbose_name='پرونده')),
            ],
            options={
                'unique_together': {('movakel', 'branch')},
            },
        ),
    ]
