# Generated by Django 5.1.5 on 2025-02-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakelbrancharchive',
            name='archive_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی'),
        ),
    ]
