# Generated by Django 5.1.5 on 2025-02-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0002_alter_movakelbrancharchive_archive_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='branchs',
            field=models.ManyToManyField(related_name='movakels', to='movakel_module.branch', verbose_name='شعبات مرتبط'),
        ),
    ]
