# Generated by Django 5.1.5 on 2025-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0003_movakel_branchs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='branchs',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.branch', verbose_name='شعبات مرتبط'),
        ),
    ]
