# Generated by Django 5.1.5 on 2025-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0004_alter_movakel_branchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='branchs',
        ),
        migrations.AlterField(
            model_name='movakel',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در URL'),
        ),
    ]
