# Generated by Django 5.1.5 on 2025-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0005_remove_movakel_branchs_alter_movakel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='branchs',
            field=models.ManyToManyField(blank=True, to='movakel_module.branch'),
        ),
    ]
