# Generated by Django 5.1.5 on 2025-02-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0006_movakel_branchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='archive_no',
        ),
    ]
