# Generated by Django 5.1.5 on 2025-02-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0007_remove_movakel_archive_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='mechanized_number',
        ),
    ]
