# Generated by Django 5.1.5 on 2025-02-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0008_remove_defensedocument_mechanized_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
