# Generated by Django 5.1.5 on 2025-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0009_alter_movakel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
