# Generated by Django 5.1.5 on 2025-02-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0010_alter_movakel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakelpayment',
            name='payment_for',
            field=models.CharField(choices=[('lawsuit', 'هزینه دادرسی'), ('attorney', 'حق\u200cالوکاله'), ('document', 'هزینه تنظیم سند'), ('other', 'سایر هزینه\u200cها')], default=12, max_length=20, verbose_name='بابت هزینه'),
            preserve_default=False,
        ),
    ]
