# Generated by Django 5.1.5 on 2025-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0011_movakelpayment_payment_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='meeting_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ملاقات'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='acceptance_method',
            field=models.CharField(blank=True, choices=[('phone', 'تلفنی'), ('in_person', 'حضوری'), ('online', 'آنلاین')], max_length=20, null=True, verbose_name='نحوه ملاقات'),
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='payment_for',
            field=models.CharField(choices=[('lawsuit', 'هزینه دادرسی'), ('document', 'هزینه تنظیم سند'), ('undergraduate fee', 'هزینه کارشناسی'), ('consulting fee', 'هزینه مشاوره'), ('attorney', 'حق الوکاله'), ('other', 'سایر هزینه\u200cها')], max_length=20, verbose_name='بابت هزینه'),
        ),
    ]
