# Generated by Django 5.1.5 on 2025-02-10 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0012_movakel_meeting_cost_movakel_meeting_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movakel',
            old_name='meeting_cost',
            new_name='acceptance_cost',
        ),
        migrations.RenameField(
            model_name='movakel',
            old_name='meeting_time',
            new_name='acceptance_time',
        ),
    ]
