# Generated by Django 5.1.5 on 2025-02-10 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0013_rename_meeting_cost_movakel_acceptance_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='acceptance_cost',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='acceptance_method',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='acceptance_time',
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('phone', 'تلفنی'), ('in_person', 'حضوری'), ('online', 'آنلاین')], max_length=20, verbose_name='نوع ملاقات')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه ملاقات')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ملاقات')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_set', to='movakel_module.movakel')),
            ],
            options={
                'verbose_name': 'ملاقات',
                'verbose_name_plural': 'ملاقات\u200cها',
            },
        ),
        migrations.AddField(
            model_name='movakel',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.meeting', verbose_name='ملاقات\u200cها'),
        ),
    ]
