# Generated by Django 5.1.5 on 2025-02-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0014_remove_movakel_acceptance_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_set', to='movakel_module.movakel', verbose_name='موکل'),
        ),
    ]
