# Generated by Django 5.1.5 on 2025-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0015_alter_meeting_movakel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('birth_year', models.IntegerField(verbose_name='سال تولد')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('meeting_type', models.CharField(choices=[('phone', 'تلفنی'), ('in_person', 'حضوری'), ('online', 'آنلاین')], max_length=20, verbose_name='نوع ملاقات')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه ملاقات')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='زمان ملاقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
            ],
            options={
                'verbose_name': 'درخواست ملاقات',
                'verbose_name_plural': 'درخواست\u200cهای ملاقات',
            },
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='meetings',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
