# Generated by Django 5.1.5 on 2025-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0016_requestmeeting_remove_movakel_meetings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='address',
            field=models.TextField(default=12, verbose_name='نشانی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='محل فعالیت'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='education',
            field=models.CharField(default=1, max_length=255, verbose_name='مدرک تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='job_title',
            field=models.CharField(default=11, max_length=255, verbose_name='عنوان شغلی'),
            preserve_default=False,
        ),
    ]
