# Generated by Django 5.1.5 on 2025-02-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0017_requestmeeting_address_requestmeeting_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='education',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام محل کار'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='education_level',
            field=models.CharField(default=11, max_length=100, verbose_name='میزان تحصیلات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='نشانی'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='job_title',
            field=models.CharField(max_length=100, verbose_name='عنوان شغل'),
        ),
    ]
