# Generated by Django 5.1.5 on 2025-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0018_remove_requestmeeting_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='job_title',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
    ]
