# Generated by Django 5.1.5 on 2025-02-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0019_remove_requestmeeting_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='id_number',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان شغلی'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='landline',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='mobile_phone',
            field=models.CharField(default=11, max_length=11, verbose_name='تلفن همراه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='سابقه کاری'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='نشانی محل سکونت'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
    ]
