# Generated by Django 5.1.5 on 2025-02-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0021_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
