# Generated by Django 5.1.5 on 2025-02-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0022_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakeltype',
            name='price',
        ),
    ]
