# Generated by Django 5.1.5 on 2025-02-14 16:39

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0023_remove_movakeltype_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('lawyer_fee', 'حق الوکاله'), ('consultation_fee', 'هزینه مشاوره'), ('meeting_fee', 'هزینه ملاقات'), ('document_review_fee', 'هزینه بررسی مدارک'), ('first_trial_fee', 'هزینه دادرسی بدوی'), ('appeal_fee', 'هزینه اعتراض'), ('petition_fee', 'هزینه لایحه'), ('execution_fee', 'هزینه اجرای احکام'), ('case_study_fee', 'هزینه مطالعه پرونده در دادگاه'), ('petition_draft_fee', 'هزینه تنظیم لایحه یا شکواییه'), ('contract_amount', 'مبلغ قرارداد'), ('contract_amount', 'مبلغ توافق شده'), ('remaining_amount', 'مبلغ باقی\u200cمانده'), ('paid_amount', 'مبلغ پرداخت شده')], max_length=50, verbose_name='نوع هزینه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار هزینه')),
                ('payment_date', django_jalali.db.models.jDateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پرداخت')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='movakel_module.movakel', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'جزئیات پرداخت',
                'verbose_name_plural': 'جزئیات پرداخت\u200cها',
            },
        ),
    ]
