# Generated by Django 5.1.5 on 2025-02-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0024_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='movakeltype',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='movakeltype',
            name='check_documents',
        ),
        migrations.RemoveField(
            model_name='movakeltype',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='movakeltype',
            name='counseling',
        ),
        migrations.AddField(
            model_name='defensedocument',
            name='defense_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه مرحله'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='bill',
            field=models.BooleanField(default=False, verbose_name='لایحه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='check_documents',
            field=models.BooleanField(default=False, verbose_name='بررسی مدارک'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='قرارداد'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='counseling',
            field=models.BooleanField(default=False, verbose_name='مشاوره'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='agreed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلف حق\u200cالوکاله توافقی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تنظیم شکواییه'),
        ),
    ]
