# Generated by Django 5.1.5 on 2025-02-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0025_remove_defensedocument_cost_remove_movakeltype_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='defense_cost',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='appeal_cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='consultation_price',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='contract_price',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='court_review_cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='defense_cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='document_review_price',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='enforcement_cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='initial_cost',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='petition_cost',
        ),
        migrations.AddField(
            model_name='defensedocument',
            name='defense_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه مرحله'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه اعتراض'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه مشاوره'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ قرارداد'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='court_review_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه مطالعه پرونده در دادگاه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه لایحه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='document_review_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه بررسی مدارک'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='enforcement_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه اجرای احکام'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه تنظیم شکواییه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='agreed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='هزینه حق\u200cالوکاله توافقی'),
        ),
    ]
