# Generated by Django 5.1.5 on 2025-02-14 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0026_remove_defensedocument_defense_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='price',
        ),
    ]
