# Generated by Django 5.1.5 on 2025-02-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0027_remove_movakel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('lawyer_fee', 'حق الوکاله'), ('consultation_fee', 'هزینه مشاوره'), ('document_review_fee', 'هزینه بررسی مدارک'), ('first_trial_fee', 'هزینه دادرسی بدوی'), ('appeal_fee', 'هزینه اعتراض'), ('petition_fee', 'هزینه لایحه'), ('execution_fee', 'هزینه اجرای احکام'), ('case_study_fee', 'هزینه مطالعه پرونده در دادگاه'), ('petition_draft_fee', 'هزینه تنظیم لایحه یا شکواییه'), ('contract_amount', 'مبلغ قرارداد'), ('contract_amount', 'مبلغ توافق شده'), ('remaining_amount', 'مبلغ باقی\u200cمانده'), ('paid_amount', 'مبلغ پرداخت شده')], max_length=50, verbose_name='نوع هزینه'),
        ),
    ]
