# Generated by Django 5.1.5 on 2025-02-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0028_alter_paymentdetail_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='custom_price',
        ),
    ]
