# Generated by Django 5.1.5 on 2025-02-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0029_remove_movakel_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
