# Generated by Django 5.1.5 on 2025-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0030_movakel_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='defense_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مرحله'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مقدار هزینه'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('consultation_fee', 'هزینه مشاوره'), ('document_review_fee', 'هزینه بررسی مدارک'), ('first_trial_fee', 'هزینه دادرسی بدوی'), ('appeal_fee', 'هزینه اعتراض'), ('petition_fee', 'هزینه لایحه'), ('execution_fee', 'هزینه اجرای احکام'), ('case_study_fee', 'هزینه مطالعه پرونده در دادگاه'), ('petition_draft_fee', 'هزینه تنظیم لایحه یا شکواییه')], max_length=50, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='agreed_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه حق\u200cالوکاله توافقی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه اعتراض'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مشاوره'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ قرارداد'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='court_review_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مطالعه پرونده در دادگاه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه لایحه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='document_review_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه بررسی مدارک'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='enforcement_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه اجرای احکام'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه تنظیم شکواییه'),
        ),
    ]
