# Generated by Django 5.1.5 on 2025-02-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0031_alter_defensedocument_defense_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ قرارداد')),
                ('remaining_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ باقی\u200cمانده')),
                ('paid_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ پرداخت شده')),
                ('movakel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_payment', to='movakel_module.movakel', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'پرداخت\u200cهای قرارداد',
                'verbose_name_plural': 'پرداخت\u200cهای قرارداد',
            },
        ),
    ]
