# Generated by Django 5.1.5 on 2025-02-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0032_contractpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='landline',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='related_movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='movakel_module.movakel', verbose_name='موکل مرتبط'),
        ),
    ]
