# Generated by Django 5.1.5 on 2025-02-17 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0033_remove_requestmeeting_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestmeeting',
            old_name='mobile_phone',
            new_name='mobile_number',
        ),
        migrations.AddField(
            model_name='movakel',
            name='request_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movakels', to='movakel_module.requestmeeting', verbose_name='درخواست ملاقات'),
        ),
    ]
