# Generated by Django 5.1.5 on 2025-02-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0034_rename_mobile_phone_requestmeeting_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='defensedocument_set',
        ),
    ]
