# Generated by Django 5.1.5 on 2025-02-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0035_remove_movakel_defensedocument_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='defensedocument_set',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.defensedocument'),
        ),
    ]
