# Generated by Django 5.1.5 on 2025-02-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0036_movakel_defensedocument_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movakel',
            options={'verbose_name': 'موکل', 'verbose_name_plural': 'موکلین'},
        ),
        migrations.RenameField(
            model_name='movakel',
            old_name='title',
            new_name='name',
        ),

        migrations.RemoveField(
            model_name='movakel',
            name='custom_price',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='received_amount',
        ),
    ]
