# Generated by Django 5.1.5 on 2025-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0037_alter_movakel_options_rename_title_movakel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=0, editable=False, max_digits=10, verbose_name='مبلغ باقی\u200cمانده'),
        ),
    ]
