# Generated by Django 5.1.5 on 2025-02-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0038_alter_contractpayment_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='birth_year',
            field=models.CharField(max_length=4, verbose_name='سال تولد'),
        ),
    ]
