# Generated by Django 5.1.5 on 2025-02-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0039_alter_requestmeeting_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان پایان ملاقات'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='identification_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع ملاقات'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس ثابت'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='related_movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='movakel_module.movakel', verbose_name='وکالت داده شده (سابقه مراجعه)؟'),
        ),
    ]
