# Generated by Django 5.1.5 on 2025-02-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0040_requestmeeting_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='duration',
            field=models.IntegerField(choices=[(15, '۱۵ دقیقه'), (30, '۳۰ دقیقه'), (60, '۱ ساعت'), (90, '۱ ساعت و نیم'), (120, '۲ ساعت')], default=60, verbose_name='مدت جلسه'),
        ),
    ]
