# Generated by Django 5.1.5 on 2025-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0041_requestmeeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='مدت جلسه'),
        ),
    ]
