# Generated by Django 5.1.5 on 2025-02-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0042_alter_requestmeeting_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='national_id',
            field=models.CharField(default=1, max_length=10, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
    ]
