# Generated by Django 5.1.5 on 2025-02-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0043_movakel_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='national_id',
        ),
    ]
