# Generated by Django 5.1.5 on 2025-02-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0044_remove_movakel_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='service_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='movakel_module.servicetype', verbose_name='نوع خدمت'),
            preserve_default=False,
        ),
    ]
