# Generated by Django 5.1.5 on 2025-02-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0046_alter_requestmeeting_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='service_type',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='service_type',
            field=models.ManyToManyField(to='movakel_module.servicetype', verbose_name='نوع خدمت مرتبط'),
        ),
    ]
