# Generated by Django 5.1.5 on 2025-02-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0047_remove_requestmeeting_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='birth_year',
            field=models.IntegerField(verbose_name='سال تولد'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='related_movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='movakel_module.movakel', verbose_name='موکل مرتبط'),
        ),
    ]
