# Generated by Django 5.1.5 on 2025-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0048_remove_requestmeeting_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='identification_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='birth_year',
            field=models.CharField(max_length=4, verbose_name='سال تولد'),
        ),
    ]
