# Generated by Django 5.1.5 on 2025-02-25 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0049_requestmeeting_identification_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان موضوع')),
            ],
            options={
                'verbose_name': 'موضوع ملاقات',
                'verbose_name_plural': 'موضوعات ملاقات',
            },
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name=' تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='related_movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='movakel_module.movakel', verbose_name='وکالت داده شده (سابقه مراجعه)؟'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_subject',
            field=models.ManyToManyField(to='movakel_module.meetingsubject', verbose_name='موضوع ملاقات'),
        ),
    ]
