# Generated by Django 5.1.5 on 2025-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0050_meetingsubject_alter_requestmeeting_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='time',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ملاقات'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ملاقات'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_subject',
            field=models.ManyToManyField(blank=True, to='movakel_module.meetingsubject', verbose_name='موضوع ملاقات'),
        ),
    ]
