# Generated by Django 5.1.5 on 2025-02-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0051_remove_requestmeeting_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='meeting_fee',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='related_movakel',
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن ثابت'),
        ),
    ]
