# Generated by Django 5.1.5 on 2025-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0052_remove_requestmeeting_meeting_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='status',
            field=models.CharField(choices=[('pending', ' مشاوره'), ('converted', ' موکل  ')], default='pending', max_length=10, verbose_name='وضعیت درخواست'),
        ),
    ]
