# Generated by Django 5.1.5 on 2025-02-26 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0053_requestmeeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='movakel_module.movakel'),
        ),
    ]
