# Generated by Django 5.1.5 on 2025-02-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0054_requestmeeting_movakel'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
    ]
