# Generated by Django 5.1.5 on 2025-02-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0055_requestmeeting_meeting_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defensedocument',
            old_name='defense_fee',
            new_name='bill_fee',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='bill_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه لایحه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='defense',
            field=models.BooleanField(default=False, verbose_name='دفاع'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='appeal_court_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دادنامه تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='mechanized_number',
            field=models.CharField(max_length=20, null=True, verbose_name='شماره مکانیزه'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='primary_court_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دادنامه بدوی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract',
            field=models.BooleanField(default=False, verbose_name='تنظیم قرارداد'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مبلغ تنظیم قرارداد'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='defense_fee',
            field=models.BooleanField(default=False, verbose_name='هزینه دفاع'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='movakel',
            field=models.CharField(max_length=255, verbose_name='نام موکل'),
        ),
    ]
