# Generated by Django 5.1.5 on 2025-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0056_rename_defense_fee_defensedocument_bill_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='court_service_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه دفتر خدمات قضائی'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='document_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه اظهارنامه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='lawsuit_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه دادخواست'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='notification_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه اخذ ابلاغیه از سامانه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه اعتراض(هزینه دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='bill_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال لوایح'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='هزینه دفاع'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی(تمبر دادرسی)'),
        ),
    ]
