# Generated by Django 5.1.5 on 2025-02-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0058_servicetype_complaint_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='complaint_fee',
        ),
    ]
