# Generated by Django 5.1.5 on 2025-02-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0059_remove_servicetype_complaint_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='archive_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی'),
        ),
    ]
