# Generated by Django 5.1.5 on 2025-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0060_branch_archive_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='archive_no',
        ),
        migrations.AddField(
            model_name='movakel',
            name='appeal_archive_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی تجدیدنظر'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='executive_archive_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی اجرای احکام'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='primary_archive_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره بایگانی بدوی'),
        ),
    ]
