# Generated by Django 5.1.5 on 2025-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0063_alter_movakel_executive_court_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='auction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مزایده'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='hearing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان رسیدگی'),
        ),
    ]
