# Generated by Django 5.1.5 on 2025-02-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0064_movakel_auction_date_movakel_hearing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakelvisit',
            name='movakel',
        ),
        migrations.RemoveField(
            model_name='movakelvisit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='visits',
        ),
        migrations.AlterField(
            model_name='movakel',
            name='final_result',
            field=models.TextField(blank=True, null=True, verbose_name='  ملاحظات'),
        ),
        migrations.DeleteModel(
            name='MovakelTag',
        ),
        migrations.DeleteModel(
            name='MovakelVisit',
        ),
    ]
