# Generated by Django 5.1.5 on 2025-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0065_remove_movakelvisit_movakel_remove_movakelvisit_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='مدت جلسه'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان ملاقات'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان پایان ملاقات'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ شروع ملاقات'),
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع ملاقات'),
        ),
    ]
