# Generated by Django 5.1.5 on 2025-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0066_requestmeeting_duration_requestmeeting_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='meeting_date',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='meeting_time',
        ),
        migrations.RemoveField(
            model_name='requestmeeting',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان خروج'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ورود'),
        ),
    ]
