# Generated by Django 5.1.5 on 2025-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0067_remove_requestmeeting_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ملاقات'),
        ),
    ]
