# Generated by Django 5.1.5 on 2025-03-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0068_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ملاقات'),
        ),
    ]
