# Generated by Django 5.1.5 on 2025-03-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0069_requestmeeting_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='related_movakel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_request_meetings', to='movakel_module.movakel', verbose_name='وکالت داده شده (سابقه مراجعه)'),
        ),
    ]
