# Generated by Django 5.1.5 on 2025-03-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0070_requestmeeting_related_movakel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('consultation_fee', 'هزینه مشاوره'), ('document_review_fee', 'هزینه بررسی مدارک'), ('contract_fee', 'هزینه تنظیم قرارداد'), ('defense_fee', 'هزینه دفاع'), ('bill_fee', 'هزینه ارسال لایحه'), ('agreed_fee', 'هزینه حق\u200cالوکاله توافقی'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('court_review_fee', 'هزینه مطالعه پرونده در دادگاه'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه'), ('lawsuit_fee', 'هزینه دادخواست')], max_length=50, verbose_name='نوع هزینه'),
        ),
    ]
