# Generated by Django 5.1.5 on 2025-03-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0071_alter_paymentdetail_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
    ]
