# Generated by Django 5.1.5 on 2025-03-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0072_alter_requestmeeting_meeting_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensedocument',
            name='defense_fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='هزینه مرحله'),
        ),
        migrations.AlterField(
            model_name='defensedocument',
            name='stage',
            field=models.CharField(choices=[('initial', 'ابتدایی'), ('appeal', 'تجدیدنظر'), ('execution', 'اجرای احکام'), ('petition', 'تنظیم لایحه')], max_length=500, verbose_name='مرحله'),
        ),
    ]
