# Generated by Django 5.1.5 on 2025-03-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0073_defensedocument_defense_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='bill_fee',
        ),
    ]
