# Generated by Django 5.1.5 on 2025-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0074_remove_defensedocument_bill_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='requestmeeting',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
