# Generated by Django 5.1.5 on 2025-03-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0075_remove_requestmeeting_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='نشانی اینترنتی'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی'),
        ),
    ]
