# Generated by Django 5.1.5 on 2025-03-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0076_alter_requestmeeting_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='meeting_time',
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت جلسه'),
        ),
    ]
