# Generated by Django 5.1.5 on 2025-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0077_remove_requestmeeting_meeting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='virtual_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فضای مجازی'),
        ),
    ]
