# Generated by Django 5.1.5 on 2025-03-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0078_requestmeeting_virtual_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakelcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='movakelcategory',
            name='is_delete',
        ),
    ]
