# Generated by Django 5.1.5 on 2025-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0079_remove_movakelcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakelcategory',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
