# Generated by Django 5.1.5 on 2025-03-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0082_remove_servicetype_court_review_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='defensedocument',
            name='content',
        ),
        migrations.DeleteModel(
            name='MovakelType',
        ),
    ]
