# Generated by Django 5.1.5 on 2025-03-22 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0083_remove_movakel_type_remove_defensedocument_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovakelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام پرونده')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'نوع پرونده',
                'verbose_name_plural': 'نوع پرونده\u200cها',
            },
        ),
        migrations.AddField(
            model_name='movakel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakeltype', verbose_name='نوع پرونده'),
        ),
    ]
