# Generated by Django 5.1.5 on 2025-03-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0084_movakeltype_movakel_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='type',
        ),
        migrations.DeleteModel(
            name='MovakelType',
        ),
    ]
