# Generated by Django 5.1.5 on 2025-03-22 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0085_remove_movakel_type_delete_movakeltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movakels', to='movakel_module.servicetype', verbose_name=' اقدامات'),
        ),
    ]
