# Generated by Django 5.1.5 on 2025-03-22 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0086_alter_movakel_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='short_description',
        ),
    ]
