# Generated by Django 5.1.5 on 2025-03-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0087_remove_movakel_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='supervision_date',
        ),
        migrations.AlterField(
            model_name='movakel',
            name='hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='وقت رسیدگی /وقت نظارت'),
        ),
    ]
