# Generated by Django 5.1.5 on 2025-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0088_remove_movakel_supervision_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_number',
        ),
        migrations.AlterField(
            model_name='movakel',
            name='executive_court_result',
            field=models.TextField(blank=True, null=True, verbose_name='عملیات اجرائی'),
        ),
    ]
