# Generated by Django 5.1.5 on 2025-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0089_remove_branch_branch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmeeting',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان ملاقات'),
        ),
    ]
