# Generated by Django 5.1.5 on 2025-03-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0090_requestmeeting_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
    ]
