# Generated by Django 5.1.5 on 2025-03-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0091_alter_requestmeeting_meeting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
