# Generated by Django 5.1.5 on 2025-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0092_alter_defensedocument_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
