# Generated by Django 5.1.5 on 2025-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0093_alter_defensedocument_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='virtual_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره فضای مجازی'),
        ),
    ]
