# Generated by Django 5.1.5 on 2025-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0094_alter_requestmeeting_virtual_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن ثابت'),
        ),
    ]
