# Generated by Django 5.1.5 on 2025-03-25 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0095_alter_requestmeeting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='virtual_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره باید فقط شامل اعداد و حداکثر 11 رقم باشد.', regex='^\\d{0,11}$')], verbose_name='شماره فضای مجازی'),
        ),
    ]
