# Generated by Django 5.1.5 on 2025-03-25 15:50

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0097_alter_requestmeeting_virtual_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmeeting',
            name='meeting_time',
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ملاقات (شمسی)'),
            preserve_default=False,
        ),
    ]
