# Generated by Django 5.1.5 on 2025-03-25 16:01

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0099_alter_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ملاقات'),
        ),
    ]
