# Generated by Django 5.1.5 on 2025-03-26 07:36

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0100_alter_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
    ]
