# Generated by Django 5.1.5 on 2025-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0101_alter_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='اخذابلاغیه'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='office_study',
            field=models.BooleanField(default=False, verbose_name='در دفتر مطالعه پرونده'),
        ),
    ]
