# Generated by Django 5.1.5 on 2025-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0102_servicetype_notification_servicetype_office_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='office_study_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه  مطالعه پرونده '),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study',
            field=models.BooleanField(default=False, verbose_name=' مطالعه پرونده '),
        ),
    ]
