# Generated by Django 5.1.5 on 2025-03-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0103_servicetype_office_study_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'اقدام', 'verbose_name_plural': 'اقدامات'},
        ),
        migrations.RenameField(
            model_name='servicetype',
            old_name='counseling',
            new_name='consultation',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='contract_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='defense_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='document_review_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='notification_fee',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='lawyer_services_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه کل خدمات وکیل'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='notification',
            field=models.BooleanField(default=False, verbose_name='اخذ ابلاغیه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study',
            field=models.BooleanField(default=False, verbose_name='مطالعه پرونده'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مطالعه پرونده'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه تنظیم شکوائیه'),
        ),
    ]
