# Generated by Django 5.1.5 on 2025-03-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0104_alter_servicetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مشاوره'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه تنظیم قرارداد'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه دفاع'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='document_review_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه بررسی مدارک'),
        ),
    ]
