# Generated by Django 5.1.5 on 2025-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0105_servicetype_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='common_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه مشترک'),
        ),
    ]
