# Generated by Django 5.1.5 on 2025-03-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0107_alter_servicetype_common_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel', verbose_name='موکل'),
        ),
    ]
