# Generated by Django 5.1.5 on 2025-03-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0109_alter_servicetype_movakel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='movakel',
        ),
    ]
