# Generated by Django 5.1.5 on 2025-03-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0110_remove_servicetype_movakel'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='movakel',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel', verbose_name='موکل'),
            preserve_default=False,
        ),
    ]
