# Generated by Django 5.1.5 on 2025-03-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0114_alter_servicetype_movakel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateField(verbose_name='تاریخ رسیدگی')),
                ('hearing_time', models.TimeField(verbose_name='زمان رسیدگی')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_schedules', to='movakel_module.movakel')),
            ],
            options={
                'verbose_name': 'وقت رسیدگی',
                'verbose_name_plural': 'وقت\u200cهای رسیدگی',
                'ordering': ['hearing_date'],
            },
        ),
    ]
