# Generated by Django 5.1.5 on 2025-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0115_hearingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
    ]
