# Generated by Django 5.1.5 on 2025-03-29 15:01

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0117_remove_movakel_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakelbrancharchive',
            name='archive_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره بایگانی'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات')),
                ('start_time', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان ورود')),
                ('end_time', models.TimeField(blank=True, default=None, null=True, verbose_name='زمان خروج')),
                ('visit_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت جلسه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('movakel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='movakel_module.movakel', verbose_name='موکل')),
            ],
            options={
                'verbose_name': 'ملاقات',
                'verbose_name_plural': 'ملاقات ها',
            },
        ),
    ]
