# Generated by Django 5.1.5 on 2025-03-29 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0118_alter_movakelbrancharchive_archive_no_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayment',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ هر قسط'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='paid_installments',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد اقساط پرداخت\u200cشده'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ پرداخت'),
         ),
        migrations.AddField(
            model_name='contractpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=12, verbose_name='مبلغ کل حق الوکاله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کل اقساط'),
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movakel_module.movakel', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ باقی\u200cمانده'),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ پرداختی')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('contract_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='movakel_module.contractpayment')),
            ],
        ),
    ]
