# Generated by Django 5.1.5 on 2025-03-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0119_remove_contractpayment_contract_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ کل حق الوکاله'),
        ),
    ]
