# Generated by Django 5.1.5 on 2025-03-29 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0120_alter_contractpayment_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ پرداخت'),
        ),
    ]
