# Generated by Django 5.1.5 on 2025-03-29 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0121_alter_contractpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='movakel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='movakel_module.movakel'),
        ),
    ]
