# Generated by Django 5.1.5 on 2025-03-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0122_installmentpayment_movakel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='movakel_module.movakel'),
        ),
    ]
