# Generated by Django 5.1.5 on 2025-03-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0123_alter_installmentpayment_movakel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل'),
        ),
    ]
