# Generated by Django 5.1.5 on 2025-03-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0124_alter_contractpayment_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpayment',
            options={'verbose_name': 'پرداخت\u200cهای حق الوکاله', 'verbose_name_plural': 'پرداخت\u200cهای حق الوکاله'},
        ),
    ]
