# Generated by Django 5.1.5 on 2025-03-29 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0125_alter_contractpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='contract_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movakel_contract_payment', to='movakel_module.contractpayment'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='appeal_archive_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره بایگانی تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='executive_archive_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره بایگانی اجرای احکام'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='executive_case_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره اجرائیه پرونده'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='primary_archive_no',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='شماره بایگانی بدوی'),
        ),
    ]
