# Generated by Django 5.1.5 on 2025-03-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0126_movakel_contract_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentpayment',
            options={'verbose_name': 'پرداخت قسطی', 'verbose_name_plural': 'پرداخت\u200cهای اقساطی'},
        ),
    ]
