# Generated by Django 5.1.5 on 2025-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0127_alter_installmentpayment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='مبلغ باقی\u200cمانده'),
        ),
    ]
