# Generated by Django 5.1.5 on 2025-03-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0128_alter_contractpayment_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayment',
            name='payment_date',
        ),
    ]
