# Generated by Django 5.1.5 on 2025-03-30 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0129_remove_contractpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ پرداخت'),
        ),
    ]
