# Generated by Django 5.1.5 on 2025-03-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0130_contractpayment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentpayment',
            options={'verbose_name': 'پرداخت حق الوکاله', 'verbose_name_plural': 'پرداخت\u200cهای حق الوکاله'},
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='paid_installments',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='total_installments',
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='movakel_module.movakel', verbose_name='نام موکل'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='contract_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='movakel_module.contractpayment', verbose_name='پرداخت ها'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='movakel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_payments', to='movakel_module.movakel', verbose_name='نام موکل'),
        ),
    ]
