# Generated by Django 5.1.5 on 2025-03-30 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0131_alter_installmentpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
    ]
