# Generated by Django 5.1.5 on 2025-03-31 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0132_alter_installmentpayment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpayment',
            options={},
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='contract_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='movakel_module.contractpayment', verbose_name='پرداخت\u200cها'),
        ),
    ]
