# Generated by Django 5.1.5 on 2025-03-31 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0133_alter_contractpayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentpayment',
            name='contract_payment',
        ),
        migrations.RemoveField(
            model_name='movakel',
            name='contract_payment',
        ),
        migrations.AlterModelOptions(
            name='installmentpayment',
            options={'verbose_name': 'قسط پرداختی', 'verbose_name_plural': 'اقساط پرداختی'},
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='movakel',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل قرارداد'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ قسط'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateField(default=datetime.date.today, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.DeleteModel(
            name='ContractPayment',
        ),
    ]
