# Generated by Django 5.1.5 on 2025-03-31 18:47

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0134_remove_installmentpayment_contract_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
    ]
