# Generated by Django 5.1.5 on 2025-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0135_installmentpayment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='bail_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ وثیقه/کفالت (تومان)'),
        ),
    ]
