# Generated by Django 5.1.5 on 2025-04-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0136_movakel_bail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='defense_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='هزینه مرحله'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل قرارداد '),
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مقدار هزینه'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه ملاقات'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اعتراض(هزینه دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='bill_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه ارسال لوایح'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='common_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='سایر هزینه ها '),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه مشاوره'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه تنظیم قرارداد'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='court_service_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دفتر خدمات قضائی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دفاع'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='document_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اظهارنامه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='document_review_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه بررسی مدارک'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='enforcement_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اجرای احکام'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی(تمبر دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='lawyer_services_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه کل خدمات وکیل'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه مطالعه پرونده'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه تنظیم شکوائیه'),
        ),
    ]
