# Generated by Django 5.1.5 on 2025-04-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0137_alter_defensedocument_defense_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='common_fee',
        ),
    ]
