# Generated by Django 5.1.5 on 2025-04-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0138_remove_servicetype_common_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اعتراض(هزینه دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='bill',
            field=models.BooleanField(blank=True, default=False, verbose_name='لایحه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='bill_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه ارسال لوایح'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='check_documents',
            field=models.BooleanField(blank=True, default=False, verbose_name='بررسی مدارک'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='consultation',
            field=models.BooleanField(blank=True, default=False, verbose_name='مشاوره'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract',
            field=models.BooleanField(blank=True, default=False, verbose_name='تنظیم قرارداد'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='court_service_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دفتر خدمات قضائی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='defense',
            field=models.BooleanField(blank=True, default=False, verbose_name='دفاع'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='document_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اظهارنامه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='enforcement_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه اجرای احکام'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دادرسی بدوی(تمبر دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='movakel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movakel_module.movakel'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='notification',
            field=models.BooleanField(blank=True, default=False, verbose_name='اخذ ابلاغیه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study',
            field=models.BooleanField(blank=True, default=False, verbose_name='مطالعه پرونده'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, verbose_name='هزینه تنظیم شکوائیه'),
        ),
    ]
