# Generated by Django 5.1.5 on 2025-04-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0139_alter_servicetype_appeal_fee_alter_servicetype_bill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه دادرسی بدوی(تمبر دادرسی)'),
        ),
    ]
