# Generated by Django 5.1.5 on 2025-04-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0142_alter_servicetype_enforcement_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='court_service_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه دفتر خدمات قضائی'),
        ),
    ]
