# Generated by Django 5.1.5 on 2025-04-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0143_alter_servicetype_court_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه تنظیم شکوائیه'),
        ),
    ]
