# Generated by Django 5.1.5 on 2025-04-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0144_alter_servicetype_petition_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='document_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه اظهارنامه'),
        ),
    ]
