# Generated by Django 5.1.5 on 2025-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0146_alter_servicetype_bill_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام کارشناس')),
                ('mobile_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره همراه')),
            ],
            options={
                'verbose_name': 'کارشناس',
                'verbose_name_plural': 'کارشناسان',
            },
        ),
        migrations.AddField(
            model_name='movakel',
            name='experts',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.expert', verbose_name='کارشناسان'),
        ),
    ]
