# Generated by Django 5.1.5 on 2025-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0147_expert_movakel_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='expertise',
            field=models.CharField(default='نامشخص', max_length=255, verbose_name='تخصص'),
        ),
    ]
