# Generated by Django 5.1.5 on 2025-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0148_expert_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='experts',
        ),
        migrations.AddField(
            model_name='movakel',
            name='expert',
            field=models.ManyToManyField(blank=True, related_name='movakels', to='movakel_module.expert', verbose_name='کارشناس'),
        ),
    ]
