# Generated by Django 5.1.5 on 2025-04-01 13:44

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0149_remove_movakel_experts_movakel_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریاااخ و زمان ملاقات'),
        ),
    ]
