# Generated by Django 5.1.5 on 2025-04-01 14:02

import django_jalali.db.models
import movakel_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0150_alter_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=movakel_module.models.upload_to_movakel, verbose_name='فایل پرونده'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
    ]
