# Generated by Django 5.1.5 on 2025-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0151_movakel_contract_date_movakel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ وکالت'),
        ),
    ]
