# Generated by Django 5.1.5 on 2025-04-01 14:32

import movakel_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0152_alter_movakel_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=movakel_module.models.upload_to_movakel, verbose_name='فایل موکل'),
        ),
    ]
