# Generated by Django 5.1.5 on 2025-04-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0153_alter_movakel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movakel',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل حق الوکاله '),
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='payment_for',
            field=models.CharField(choices=[('lawsuit', 'هزینه دادرسی'), ('document', 'هزینه تنظیم سند'), ('undergraduate fee', 'هزینه کارشناسی'), ('consulting fee', 'هزینه مشاوره'), ('other', 'سایر هزینه\u200cها')], max_length=20, verbose_name='بابت هزینه'),
        ),
    ]
