# Generated by Django 5.1.5 on 2025-04-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0154_alter_movakel_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'مراجعه', 'verbose_name_plural': 'مراجعات'},
        ),
    ]
