# Generated by Django 5.1.5 on 2025-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0155_alter_visit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'مراجعه', 'verbose_name_plural': 'ها'},
        ),
    ]
