# Generated by Django 5.1.5 on 2025-04-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0156_alter_visit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='appeal_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_movakels', to='movakel_module.branch', verbose_name='شعبه تجدیدنظر'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='executive_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executive_branches', to='movakel_module.branch', verbose_name='شعبه اجرای احکام'),
        ),
        migrations.AddField(
            model_name='movakel',
            name='primary_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_movakels', to='movakel_module.branch', verbose_name='شعبه بدوی'),
        ),
    ]
