# Generated by Django 5.1.5 on 2025-04-02 20:01

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0157_movakel_appeal_branch_movakel_executive_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان درخواست'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
    ]
