# Generated by Django 5.1.5 on 2025-04-04 19:55

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0158_alter_requestmeeting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'مراجعه', 'verbose_name_plural': 'مراجعات'},
        ),
        migrations.AlterField(
            model_name='defensedocument',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='hearingschedule',
            name='hearing_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ جلسه رسیدگی'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='due_date',
            field=django_jalali.db.models.jDateField(default=datetime.date.today, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='appeal_court_notification_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ابلاغ تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='auction_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مزایده'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='contract_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ وکالت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='executive_case_notification_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ابلاغ اجرائیه پرونده'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='hearing_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='وقت رسیدگی /وقت نظارت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='primary_court_notification_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ ابلاغ بدوی'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='uploaded_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
    ]
