# Generated by Django 5.1.5 on 2025-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0159_alter_visit_options_alter_defensedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ قسط'),
        ),
    ]
