# Generated by Django 5.1.5 on 2025-04-17 10:23

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0160_alter_installmentpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentpayment',
            name='due_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ پرداخت'),
        ),
    ]
