# Generated by Django 5.1.5 on 2025-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0161_alter_installmentpayment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='stage',
            field=models.CharField(choices=[('initial', 'بدوی'), ('appeal', 'تجدیدنظر'), ('execution', 'اجرای احکام'), ('petition', 'تنظیم لایحه')], max_length=500, verbose_name='مرحله'),
        ),
    ]
