# Generated by Django 5.1.5 on 2025-04-18 07:27

import django.utils.timezone
import jdatetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0162_alter_defensedocument_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensedocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='defensedocument',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='hearingschedule',
            name='hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ جلسه رسیدگی'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='due_date',
            field=models.DateField(default=jdatetime.date.today, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='installmentpayment',
            name='payment_date',
            field=models.DateField(default=jdatetime.date.today, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='appeal_court_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ تجدیدنظر'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='auction_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مزایده'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ وکالت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='executive_case_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ اجرائیه پرونده'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='وقت رسیدگی /وقت نظارت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='primary_court_notification_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ابلاغ بدوی'),
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان ملاقات'),
        ),
    ]
