# Generated by Django 5.1.5 on 2025-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0163_alter_defensedocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ملاقات'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ملاقات (شمسی)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت جلسه (دقیقه)'),
        ),
    ]
