# Generated by Django 5.1.5 on 2025-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0164_alter_requestmeeting_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ مراجعه (شمسی)'),
        ),
    ]
