# Generated by Django 5.1.5 on 2025-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0165_alter_visit_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ملاقات'),
        ),
    ]
