# Generated by Django 5.1.5 on 2025-04-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0166_alter_requestmeeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='notification_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='هزینه اخذ ابلاغیه از سامانه'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('consultation_fee', 'هزینه مشاوره'), ('document_review_fee', 'هزینه بررسی مدارک'), ('contract_fee', 'هزینه تنظیم قراردادهای متفرقه'), ('defense_fee', 'هزینه دفاع'), ('bill_fee', 'هزینه ارسال لایحه'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه')], max_length=50, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه تنظیم قراردهای متفرقه'),
        ),
    ]
