# Generated by Django 5.1.5 on 2025-04-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0167_servicetype_notification_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='defense_fee',
        ),
    ]
