# Generated by Django 5.1.5 on 2025-04-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0168_remove_defensedocument_defense_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='notification_fee',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='هزینه اخذ ابلاغیه از سامانه'),
        ),
    ]
