# Generated by Django 5.1.5 on 2025-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0169_alter_servicetype_notification_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='defensedocument',
            name='defense_fee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='هزینه مرحله'),
        ),
    ]
