# Generated by Django 5.1.5 on 2025-04-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0170_defensedocument_defense_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensedocument',
            name='defense_fee',
        ),
    ]
