# Generated by Django 5.1.5 on 2025-04-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0171_remove_defensedocument_defense_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='defense_fee',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='document_review_fee',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='miscellaneous_expenses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه\u200cهای متفرقه (اوراق، CD، و...)'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='travel_expenses',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه سفر (هتل، وسیله نقلیه و...)'),
        ),
    ]
