# Generated by Django 5.1.5 on 2025-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0172_remove_servicetype_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='miscellaneous_expenses',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='travel_expenses',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه مشاوره'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='defense_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه دفاع'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='document_review_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه بررسی مدارک'),
        ),
    ]
