# Generated by Django 5.1.5 on 2025-04-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0174_remove_servicetype_defense_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='consultation_fee',
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='payment_for',
            field=models.CharField(choices=[('lawsuit', 'هزینه دادرسی'), ('document', 'هزینه تنظیم سند'), ('undergraduate fee', 'هزینه کارشناسی'), ('other', 'سایر هزینه\u200cها')], max_length=20, verbose_name='بابت هزینه'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('document_review_fee', 'هزینه بررسی مدارک'), ('contract_fee', 'هزینه تنظیم قراردادهای متفرقه'), ('bill_fee', 'هزینه ارسال لایحه'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه')], max_length=50, verbose_name='نوع هزینه'),
        ),
    ]
