# Generated by Django 5.1.5 on 2025-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0176_servicetype_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='consultation_fee',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='travel_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه سفر'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('travel_fee', 'هزینه سفر'), ('document_review_fee', 'هزینه بررسی مدارک'), ('contract_fee', 'هزینه تنظیم قراردادهای متفرقه'), ('bill_fee', 'هزینه ارسال لایحه'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه')], max_length=50, verbose_name='نوع هزینه'),
        ),
    ]
