# Generated by Django 5.1.5 on 2025-04-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0177_remove_servicetype_consultation_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='document_review_fee',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='miscellaneous_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه های متفرقه(اوراق ، سی دی و غیره)'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('travel_fee', 'هزینه سفر'), ('miscellaneous_fee', 'هزینه های متفرقه(اوراق ، سی  دیو غیره) '), ('contract_fee', 'هزینه تنظیم قراردادهای متفرقه'), ('bill_fee', 'هزینه ارسال لایحه'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه')], max_length=50, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract',
            field=models.BooleanField(blank=True, default=False, verbose_name='تنظیم قراردهای متفرقه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='travel_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='هزینه سفر(هتل ،وسیله نقلیه و غیره)'),
        ),
    ]
