# Generated by Django 5.1.5 on 2025-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0178_remove_servicetype_document_review_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmeeting',
            name='status',
            field=models.CharField(choices=[('pending', 'مشاوره'), ('converted', 'موکل')], default='pending', max_length=10, verbose_name='وضعیت درخواست'),
        ),
        migrations.DeleteModel(
            name='HearingSchedule',
        ),
    ]
