# Generated by Django 5.1.5 on 2025-04-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0179_alter_requestmeeting_status_delete_hearingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='category',
        ),
        migrations.AddField(
            model_name='movakel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movakel_categories', to='movakel_module.movakelcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
