# Generated by Django 6.0.6 on 2026-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0180_remove_movakel_category_movakel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='case_status',
            field=models.CharField(choices=[('in_progress', 'در جریان'), ('appeal', 'تجدیدنظر'), ('execution', 'اجرای حکم'), ('closed', 'مختومه'), ('archived', 'بایگانی')], default='in_progress', max_length=20, verbose_name='وضعیت پرونده'),
        ),
    ]
