# Generated by Django 6.0.6 on 2026-07-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0181_movakel_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movakel',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='movakel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_type', to='movakel_module.movakel'),
        ),
    ]
