# Generated by Django 4.2.16 on 2026-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0184_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='movakel',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
