# Generated by Django 4.2.16 on 2026-09-10 12:37

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0185_movakel_national_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.AlterModelOptions(
            name='pdffile',
            options={'verbose_name': 'فایل pdf', 'verbose_name_plural': 'فایل های pdf'},
        ),
        migrations.AlterField(
            model_name='movakel',
            name='final_result',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='hearing_date',
            field=models.DateField(blank=True, null=True, verbose_name='وقت رسیدگی / وقت نظارت'),
        ),
        migrations.AlterField(
            model_name='movakel',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ کل حق الوکاله'),
        ),
        migrations.AlterField(
            model_name='movakelpayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ پرداختی'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مقدار هزینه'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment_type',
            field=models.CharField(choices=[('travel_fee', 'هزینه سفر'), ('miscellaneous_fee', 'هزینه\u200cهای متفرقه'), ('contract_fee', 'هزینه تنظیم قراردادهای متفرقه'), ('bill_fee', 'هزینه ارسال لایحه'), ('initial_fee', 'هزینه دادرسی بدوی (تمبر دادرسی)'), ('appeal_fee', 'هزینه اعتراض (هزینه دادرسی)'), ('enforcement_fee', 'هزینه اجرای احکام'), ('petition_fee', 'هزینه تنظیم شکواییه'), ('court_service_fee', 'هزینه دفتر خدمات قضائی'), ('notification_fee', 'هزینه اخذ ابلاغیه از سامانه'), ('document_fee', 'هزینه اظهارنامه')], max_length=50, verbose_name='نوع هزینه'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='meeting_fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='هزینه ملاقات'),
        ),
        migrations.AlterField(
            model_name='requestmeeting',
            name='virtual_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره باید فقط شامل اعداد و حداکثر ۱۱ رقم باشد.', regex='^\\d{1,11}$')], verbose_name='شماره فضای مجازی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='appeal_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه اعتراض (هزینه دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='bill_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال لوایح'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract',
            field=models.BooleanField(blank=True, default=False, verbose_name='تنظیم قراردادهای متفرقه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='contract_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه تنظیم قراردادهای متفرقه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='court_service_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه دفتر خدمات قضائی'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='document_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه اظهارنامه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='enforcement_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه اجرای احکام'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='initial_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه دادرسی بدوی (تمبر دادرسی)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='lawyer_services_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه کل خدمات وکیل'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='miscellaneous_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه\u200cهای متفرقه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='notification_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه اخذ ابلاغیه از سامانه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='office_study_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه مطالعه پرونده'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='petition_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه تنظیم شکوائیه'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='travel_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه سفر (هتل، وسیله نقلیه و غیره)'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ مراجعه (شمسی)'),
        ),
        migrations.AddIndex(
            model_name='movakelbrancharchive',
            index=models.Index(fields=['movakel', 'branch'], name='movakel_mod_movakel_b80bd1_idx'),
        ),
    ]
