# Generated by Django 4.2.16 on 2026-09-18 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movakel_module', '0186_delete_meeting_alter_pdffile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovakelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان در URL')),
            ],
            options={
                'verbose_name': 'نوع پرونده',
                'verbose_name_plural': 'انواع پرونده',
            },
        ),
        migrations.AddField(
            model_name='movakel',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movakels', to='movakel_module.movakeltype', verbose_name='نوع پرونده'),
        ),
    ]
