# Generated by Django 5.1.5 on 2025-02-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_alter_articlecomment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_date',
        ),
    ]
