# Generated by Django 5.1.5 on 2025-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0010_remove_article_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='files/articles/pdf/', verbose_name='فایل PDF'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='files/articles/word/', verbose_name='فایل Word'),
        ),
    ]
