# Generated by Django 5.1.5 on 2025-03-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0011_remove_article_text_article_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
